config/routes.rb
Rails.application.routes.draw do
  resources :diagnoses

  resources :diseases

  resources :visits

  resources :doctors

  resources :patients

  root 'patients#index'
  get 'doctors/index'
  get 'visits/index'
  get 'diseases/index'
  get 'diagnoses/index'

end

app/controllers/diseases_controller.rb
class DiseasesController < ApplicationController
  before_action :set_disease, only: [:show, :edit, :update, :destroy]

  # GET /diseases
  # GET /diseases.json
  def index
    @diseases = Disease.all
  end

  # GET /diseases/1
  # GET /diseases/1.json
  def show
  end

  # GET /diseases/new
  def new
    @disease = Disease.new
  end

  # GET /diseases/1/edit
  def edit
  end

  # POST /diseases
  # POST /diseases.json
  def create
    @disease = Disease.new(disease_params)

    respond_to do |format|
      if @disease.save
        format.html { redirect_to @disease, notice: 'Disease was successfully created.' }
        format.json { render :show, status: :created, location: @disease }
      else
        format.html { render :new }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /diseases/1
  # PATCH/PUT /diseases/1.json
  def update
    respond_to do |format|
      if @disease.update(disease_params)
        format.html { redirect_to @disease, notice: 'Disease was successfully updated.' }
        format.json { render :show, status: :ok, location: @disease }
      else
        format.html { render :edit }
        format.json { render json: @disease.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /diseases/1
  # DELETE /diseases/1.json
  def destroy
    @disease.destroy
    respond_to do |format|
      format.html { redirect_to diseases_url, notice: 'Disease was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disease
      @disease = Disease.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disease_params
      params.require(:disease).permit(:name, :description)
    end
end

app/helpers/diseases_helper.rb
module DiseasesHelper
end

app/views/diseases/_form.html.erb
<%= form_for(@disease) do |f| %>
  <% if @disease.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disease.errors.count, "error") %> prohibited this disease from being saved:</h2>

      <ul>
      <% @disease.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/diseases/edit.html.erb
<h1>Editing disease</h1>

<%= render 'form' %>

<%= link_to 'Show', @disease %> |
<%= link_to 'Back', diseases_path %>

app/views/diseases/index.html.erb
<h1>Listing diseases</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @diseases.each do |disease| %>
      <tr>
        <td><%= disease.id %></td>
        <td><%= disease.name %></td>

        <td><%= link_to 'Show', disease %></td>
        <td><%= link_to 'Edit', edit_disease_path(disease) %></td>
        <td><%= link_to 'Destroy', disease, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disease', new_disease_path %>

app/views/diseases/new.html.erb
<h1>New disease</h1>

<%= render 'form' %>

<%= link_to 'Back', diseases_path %>

app/views/diseases/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @disease.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @disease.description %>
</p>

<%= link_to 'Edit', edit_disease_path(@disease) %> |
<%= link_to 'Back', diseases_path %>